version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=wdpai_projekt
      - POSTGRES_USER=User123
      - POSTGRES_PASSWORD=Tajne123
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/

